In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
indep_hev_summary = pd.read_csv('indep/indep_limit_summary.csv')
indep_hev_summary

,Unnamed: 0,offertimes,collection_size,indep_rep,indep_rep_runtime,indep_rep_runtime_se,indep_total_loss,indep_total_loss_se,indep_avg_loss,indep_avg_loss_se,indep_limit_runtime,indep_limit_runtime_se
0,0,20,29,0.03,0.000339,0.000013,0.546409,0.074680,0.000071,0.000010,0.367639,0.026441
1,1,30,24,0.05,0.000391,0.000008,0.420489,0.065269,0.000056,0.000009,0.174910,0.015659
2,2,40,19,0.14,0.000328,0.000008,0.267636,0.058305,0.000036,0.000008,0.063870,0.005008
3,3,50,15,0.39,0.000203,0.000008,0.175779,0.043782,0.000024,0.000006,0.019541,0.001825
4,4,60,13,0.55,0.000153,0.000006,0.140255,0.041082,0.000020,0.000006,0.008138,0.001006

In [7]:
pos_hev_summary = pd.read_csv('pos/pos_limit_summary.csv')
pos_hev_summary

,Unnamed: 0,offertimes,collection_size,pos_rep,pos_rep_runtime,pos_rep_runtime_se,pos_total_loss,pos_total_loss_se,pos_avg_loss,pos_avg_loss_se,pos_limit_runtime,pos_limit_runtime_se
0,0,20,29,0.10,0.000312,0.000011,4.206145,0.669515,0.000549,0.000087,0.642977,0.070480
1,1,30,24,0.15,0.000377,0.000012,3.280138,0.595731,0.000436,0.000079,0.240994,0.027063
2,2,40,19,0.20,0.000324,0.000009,2.201853,0.453980,0.000299,0.000062,0.084032,0.007429
3,3,50,15,0.30,0.000218,0.000009,1.237821,0.405866,0.000172,0.000056,0.028430,0.002758
4,4,60,13,0.48,0.000168,0.000005,0.871767,0.362797,0.000123,0.000051,0.011931,0.001705

In [14]:
rep_correlation_summary = pd.concat([indep_hev_summary['offertimes'],
                                     indep_hev_summary['collection_size'],
                                     indep_hev_summary['indep_rep'],
                                     indep_hev_summary['indep_rep_runtime'],
                                     indep_hev_summary['indep_rep_runtime_se'],
                                     pos_hev_summary['pos_rep'],
                                     pos_hev_summary['pos_rep_runtime'],  
                                     pos_hev_summary['pos_rep_runtime_se']
                                     ],axis=1)
rep_correlation_summary.to_csv('coupla_repsentation.csv')
rep_correlation_summary

,offertimes,collection_size,indep_rep,indep_rep_runtime,indep_rep_runtime_se,pos_rep,pos_rep_runtime,pos_rep_runtime_se
0,20,29,0.03,0.000339,0.000013,0.10,0.000312,0.000011
1,30,24,0.05,0.000391,0.000008,0.15,0.000377,0.000012
2,40,19,0.14,0.000328,0.000008,0.20,0.000324,0.000009
3,50,15,0.39,0.000203,0.000008,0.30,0.000218,0.000009
4,60,13,0.55,0.000153,0.000006,0.48,0.000168,0.000005

In [15]:
limit_correlation_summary = pd.concat([indep_hev_summary['offertimes'],
                                     indep_hev_summary['collection_size'],
                                     indep_hev_summary['indep_avg_loss'],
                                     indep_hev_summary['indep_avg_loss_se'],
                                     indep_hev_summary['indep_limit_runtime'],
                                     indep_hev_summary['indep_limit_runtime_se'],
                                     pos_hev_summary['pos_avg_loss'],
                                     pos_hev_summary['pos_avg_loss_se'],
                                     pos_hev_summary['pos_limit_runtime'],
                                     pos_hev_summary['pos_limit_runtime_se']
                                     ],axis=1)
limit_correlation_summary.to_csv('coupla_limit.csv')
limit_correlation_summary

,offertimes,collection_size,indep_avg_loss,indep_avg_loss_se,indep_limit_runtime,indep_limit_runtime_se,pos_avg_loss,pos_avg_loss_se,pos_limit_runtime,pos_limit_runtime_se
0,20,29,0.000071,0.000010,0.367639,0.026441,0.000549,0.000087,0.642977,0.070480
1,30,24,0.000056,0.000009,0.174910,0.015659,0.000436,0.000079,0.240994,0.027063
2,40,19,0.000036,0.000008,0.063870,0.005008,0.000299,0.000062,0.084032,0.007429
3,50,15,0.000024,0.000006,0.019541,0.001825,0.000172,0.000056,0.028430,0.002758
4,60,13,0.000020,0.000006,0.008138,0.001006,0.000123,0.000051,0.011931,0.001705