In [1]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import math
import gurobipy as gp
from gurobipy import GRB
import itertools
from itertools import combinations
from itertools import permutations
from random import choice
import json
import cvxpy as cp
from tkinter import _flatten
import copy
import time
import scipy.stats as stats
from scipy.stats import gumbel_r

In [2]:
np.random.seed(1)
random.seed(1)

In [3]:
raw_jd_choice = pd.read_excel('choices.xlsm')  
offertimes = raw_jd_choice.groupby('clickset')['clicknum'].sum()[raw_jd_choice.clickset.unique()]
#offertimes.to_csv('offertimes.csv')
inc_prod_num = raw_jd_choice['clickset'].value_counts()[raw_jd_choice.clickset.unique()]
#inc_prod_num.to_csv('inc_prod_num.csv')
choice_prob = raw_jd_choice['clicknum'] / raw_jd_choice.groupby('clickset')['clicknum'].transform('sum')
raw_jd_choice['choice prob'] = choice_prob

assortment_info_df = pd.DataFrame({'assortments':raw_jd_choice.clickset.unique(),'offer_times':offertimes,'includ_prod_num':inc_prod_num})

# extended assortments with outside option 
# transfer to list
clickset = raw_jd_choice['clickset']
clickset_list = []
for cset in clickset:
    num_lst = json.loads(cset)
    #clickset_list.append(num_lst+[0])
    clickset_list.append([0]+num_lst)
raw_jd_choice['clickset'] = clickset_list

# all purchase options in each assortment
purchaseset = raw_jd_choice['purchaseset']
purchaseset_list = []
for pset in purchaseset:
    num_lst = json.loads(pset)
    purchaseset_list.append(num_lst)
raw_jd_choice['purchaseset'] = purchaseset_list

purchasenum_list = raw_jd_choice['clicknum'].tolist()
jd_choice=pd.DataFrame({'clickset':clickset_list,'purchaseset':purchaseset_list,'purchasenum':purchasenum_list,'choice prob':choice_prob})

n = 9 # product size top 8 products and outside option
print('there are {} different products'.format(n))
collection = []
for cset in clickset_list:
    if cset not in collection:
        collection.append(cset)
print('there are {} different assortments'.format(len(collection)))

assortment_info_df['assortments'] = collection
choice_collection = np.zeros((n,len(collection)))
global_num = 0
for i in range(len(collection)):
    local_num =0
    while(local_num < inc_prod_num[i]):
        if purchaseset_list[global_num][0] in collection[i]:
            choice_collection[purchaseset_list[global_num][0]][i] = choice_prob[global_num]
            global_num = global_num +1
            local_num = local_num +1
        else:
            print('error!')

there are 9 different products
there are 134 different assortments

In [4]:
assortment_info_df_15 = assortment_info_df[(assortment_info_df['offer_times']>=15)]
assortments_15 = []
for i in range(len(assortment_info_df_15['assortments'])):
    assortments_15.append(assortment_info_df_15['assortments'][i])


jd_choice_15 = pd.DataFrame(columns=jd_choice.columns)

num = 0
for i in range(len(jd_choice)):
    if jd_choice['clickset'][i] in assortments_15:
        jd_choice_15.loc[num] = jd_choice.loc[i]
        num = num+1 

collection_15 = assortment_info_df_15['assortments']
choice_collection_15 = np.zeros((n,len(collection_15)))

frequency_collection_15 = np.zeros((n,len(collection_15)))

purchaseset_list_15 = jd_choice_15['purchaseset'].tolist()

inc_prod_num_15 = assortment_info_df_15['includ_prod_num']
choice_prob_15 = jd_choice_15['choice prob']
frequency_15 = jd_choice_15['purchasenum']

global_num = 0
for i in range(len(collection_15)):
    local_num =0
    while(local_num < inc_prod_num_15[i]):
        if purchaseset_list_15[global_num][0] in assortments_15[i]:
            choice_collection_15[purchaseset_list_15[global_num][0]][i] = choice_prob_15[global_num]
            frequency_collection_15[purchaseset_list_15[global_num][0]][i] = frequency_15[global_num]
            global_num = global_num +1
            local_num = local_num +1
        else:
            print(purchaseset_list_15[global_num])
            print(assortments_15[i])
            print('error!')
            break

offer_times_15 = assortment_info_df_15['offer_times'].tolist()
print('the number of assortments with at least 15 purchases is',len(assortments_15))

the number of assortments with at least 15 purchases is 38

In [5]:
assortment_info_df_20 = assortment_info_df[(assortment_info_df['offer_times']>=20)]
assortments_20 = []
for i in range(len(assortment_info_df_20['assortments'])):
    assortments_20.append(assortment_info_df_20['assortments'][i])


jd_choice_20 = pd.DataFrame(columns=jd_choice.columns)

num = 0
for i in range(len(jd_choice)):
    if jd_choice['clickset'][i] in assortments_20:
        jd_choice_20.loc[num] = jd_choice.loc[i]
        num = num+1 

collection_20 = assortment_info_df_20['assortments']
choice_collection_20 = np.zeros((n,len(collection_20)))

frequency_collection_20 = np.zeros((n,len(collection_20)))

purchaseset_list_20 = jd_choice_20['purchaseset'].tolist()

inc_prod_num_20 = assortment_info_df_20['includ_prod_num']
choice_prob_20 = jd_choice_20['choice prob']
frequency_20 = jd_choice_20['purchasenum']

global_num = 0
for i in range(len(collection_20)):
    local_num =0
    while(local_num < inc_prod_num_20[i]):
        if purchaseset_list_20[global_num][0] in assortments_20[i]:
            choice_collection_20[purchaseset_list_20[global_num][0]][i] = choice_prob_20[global_num]
            frequency_collection_20[purchaseset_list_20[global_num][0]][i] = frequency_20[global_num]
            global_num = global_num +1
            local_num = local_num +1
        else:
            print(purchaseset_list_20[global_num])
            print(assortments_20[i])
            print('error!')
            break


offer_times_20 = assortment_info_df_20['offer_times'].tolist()
print('the number of assortments with at least 20 purchases is',len(assortments_20))

the number of assortments with at least 20 purchases is 29

In [6]:
assortment_info_df_30 = assortment_info_df[(assortment_info_df['offer_times']>=30)]
assortments_30 = []
for i in range(len(assortment_info_df_30['assortments'])):
    assortments_30.append(assortment_info_df_30['assortments'][i])


jd_choice_30 = pd.DataFrame(columns=jd_choice.columns)

num = 0
for i in range(len(jd_choice)):
    if jd_choice['clickset'][i] in assortments_30:
        jd_choice_30.loc[num] = jd_choice.loc[i]
        num = num+1 

collection_30 = assortment_info_df_30['assortments']
choice_collection_30 = np.zeros((n,len(collection_30)))

frequency_collection_30 = np.zeros((n,len(collection_30)))

purchaseset_list_30 = jd_choice_30['purchaseset'].tolist()

inc_prod_num_30 = assortment_info_df_30['includ_prod_num']
choice_prob_30 = jd_choice_30['choice prob']
frequency_30 = jd_choice_30['purchasenum']

global_num = 0
for i in range(len(collection_30)):
    local_num =0
    while(local_num < inc_prod_num_30[i]):
        if purchaseset_list_30[global_num][0] in assortments_30[i]:
            choice_collection_30[purchaseset_list_30[global_num][0]][i] = choice_prob_30[global_num]
            frequency_collection_30[purchaseset_list_30[global_num][0]][i] = frequency_30[global_num]
            global_num = global_num +1
            local_num = local_num +1
        else:
            print(purchaseset_list_30[global_num])
            print(assortments_30[i])
            print('error!')
            break



offer_times_30 = assortment_info_df_30['offer_times'].tolist()
print('the number of assortments with at least 30 purchases is',len(assortments_30))

the number of assortments with at least 30 purchases is 24

In [7]:
assortment_info_df_40 = assortment_info_df[(assortment_info_df['offer_times']>=40)]
assortments_40 = []
for i in range(len(assortment_info_df_40['assortments'])):
    assortments_40.append(assortment_info_df_40['assortments'][i])


jd_choice_40 = pd.DataFrame(columns=jd_choice.columns)

num = 0
for i in range(len(jd_choice)):
    if jd_choice['clickset'][i] in assortments_40:
        jd_choice_40.loc[num] = jd_choice.loc[i]
        num = num+1 

collection_40 = assortment_info_df_40['assortments']
choice_collection_40 = np.zeros((n,len(collection_40)))

frequency_collection_40 = np.zeros((n,len(collection_40)))

purchaseset_list_40 = jd_choice_40['purchaseset'].tolist()

inc_prod_num_40 = assortment_info_df_40['includ_prod_num']
choice_prob_40 = jd_choice_40['choice prob']
frequency_40 = jd_choice_40['purchasenum']

global_num = 0
for i in range(len(collection_40)):
    local_num =0
    while(local_num < inc_prod_num_40[i]):
        if purchaseset_list_40[global_num][0] in assortments_40[i]:
            choice_collection_40[purchaseset_list_40[global_num][0]][i] = choice_prob_40[global_num]
            frequency_collection_40[purchaseset_list_40[global_num][0]][i] = frequency_40[global_num]
            global_num = global_num +1
            local_num = local_num +1
        else:
            print(purchaseset_list_40[global_num])
            print(assortments_40[i])
            print('error!')
            break



offer_times_40 = assortment_info_df_40['offer_times'].tolist()
print('the number of assortments with at least 40 purchases is',len(assortments_40))

the number of assortments with at least 40 purchases is 19

In [8]:
assortment_info_df_50 = assortment_info_df[(assortment_info_df['offer_times']>=50)]
assortments_50 = []
for i in range(len(assortment_info_df_50['assortments'])):
    assortments_50.append(assortment_info_df_50['assortments'][i])


jd_choice_50 = pd.DataFrame(columns=jd_choice.columns)

num = 0
for i in range(len(jd_choice)):
    if jd_choice['clickset'][i] in assortments_50:
        jd_choice_50.loc[num] = jd_choice.loc[i]
        num = num+1 

collection_50 = assortment_info_df_50['assortments']
choice_collection_50 = np.zeros((n,len(collection_50)))

frequency_collection_50 = np.zeros((n,len(collection_50)))

purchaseset_list_50 = jd_choice_50['purchaseset'].tolist()

inc_prod_num_50 = assortment_info_df_50['includ_prod_num']
choice_prob_50 = jd_choice_50['choice prob']
frequency_50 = jd_choice_50['purchasenum']

global_num = 0
for i in range(len(collection_50)):
    local_num =0
    while(local_num < inc_prod_num_50[i]):
        if purchaseset_list_50[global_num][0] in assortments_50[i]:
            choice_collection_50[purchaseset_list_50[global_num][0]][i] = choice_prob_50[global_num]
            frequency_collection_50[purchaseset_list_50[global_num][0]][i] = frequency_50[global_num]
            global_num = global_num +1
            local_num = local_num +1
        else:
            print(purchaseset_list_50[global_num])
            print(assortments_50[i])
            print('error!')
            break


offer_times_50 = assortment_info_df_50['offer_times'].tolist()
print('the number of assortments with at least 50 purchases is',len(assortments_50))

the number of assortments with at least 50 purchases is 15

In [9]:
assortment_info_df_60 = assortment_info_df[(assortment_info_df['offer_times']>=60)]
assortments_60 = []
for i in range(len(assortment_info_df_60['assortments'])):
    assortments_60.append(assortment_info_df_60['assortments'][i])


jd_choice_60 = pd.DataFrame(columns=jd_choice.columns)

num = 0
for i in range(len(jd_choice)):
    if jd_choice['clickset'][i] in assortments_60:
        jd_choice_60.loc[num] = jd_choice.loc[i]
        num = num+1 

collection_60 = assortment_info_df_60['assortments']
choice_collection_60 = np.zeros((n,len(collection_60)))

frequency_collection_60 = np.zeros((n,len(collection_60)))

purchaseset_list_60 = jd_choice_60['purchaseset'].tolist()

inc_prod_num_60 = assortment_info_df_60['includ_prod_num']
choice_prob_60 = jd_choice_60['choice prob']
frequency_60 = jd_choice_60['purchasenum']

global_num = 0
for i in range(len(collection_60)):
    local_num =0
    while(local_num < inc_prod_num_60[i]):
        if purchaseset_list_60[global_num][0] in assortments_60[i]:
            choice_collection_60[purchaseset_list_60[global_num][0]][i] = choice_prob_60[global_num]
            frequency_collection_60[purchaseset_list_60[global_num][0]][i] = frequency_60[global_num]
            global_num = global_num +1
            local_num = local_num +1
        else:
            print(purchaseset_list_60[global_num])
            print(assortments_60[i])
            print('error!')
            break


offer_times_60 = assortment_info_df_60['offer_times'].tolist()
print('the number of assortments with at least 60 purchases is',len(assortments_60))

the number of assortments with at least 60 purchases is 13

In [10]:
''' def new_data_w_at_least_2_products(n,curr_collection,curr_choice_collection,curr_offertimes):
    
    pre_new_collection = []
    new_collection_indices = []
    new_offertimes = []
    
    for i in range(len(curr_collection)):
        if len(curr_collection[i])>2:
            pre_new_collection.append(curr_collection[i][1:])
            new_collection_indices.append(i)
            new_offertimes.append(curr_offertimes[i])
            
    # Reduce values of all elements by 1
    new_collection = [[element - 1 for element in sublist] for sublist in pre_new_collection]

    new_choice_collection = np.zeros((n-1,len(new_collection_indices)))
    for i in range(len(new_collection_indices)):
        new_choice_collection[:,i] = curr_choice_collection[1:,new_collection_indices[i]]/np.sum(curr_choice_collection[1:,new_collection_indices[i]])
            
    return new_collection,new_choice_collection,new_offertimes '''

' def new_data_w_at_least_2_products(n,curr_collection,curr_choice_collection,curr_offertimes):\n    \n    pre_new_collection = []\n    new_collection_indices = []\n    new_offertimes = []\n    \n    for i in range(len(curr_collection)):\n        if len(curr_collection[i])>2:\n            pre_new_collection.append(curr_collection[i][1:])\n            new_collection_indices.append(i)\n            new_offertimes.append(curr_offertimes[i])\n            \n    # Reduce values of all elements by 1\n    new_collection = [[element - 1 for element in sublist] for sublist in pre_new_collection]\n\n    new_choice_collection = np.zeros((n-1,len(new_collection_indices)))\n    for i in range(len(new_collection_indices)):\n        new_choice_collection[:,i] = curr_choice_collection[1:,new_collection_indices[i]]/np.sum(curr_choice_collection[1:,new_collection_indices[i]])\n            \n    return new_collection,new_choice_collection,new_offertimes '

In [11]:
''' new_assortment_15,new_choice_collection_15,new_offer_times_15 = new_data_w_at_least_2_products(n,assortments_15,choice_collection_15,offer_times_15)
print('the new size of the collection with offertimes at least 15 is ',len(new_assortment_15))

new_assortment_20,new_choice_collection_20,new_offer_times_20 = new_data_w_at_least_2_products(n,assortments_20,choice_collection_20,offer_times_20)
print('the new size of the collection with offertimes at least 20 is ',len(new_assortment_20))

new_assortment_30,new_choice_collection_30,new_offer_times_30 = new_data_w_at_least_2_products(n,assortments_30,choice_collection_30,offer_times_30)
print('the new size of the collection with offertimes at least 30 is ',len(new_assortment_30))

new_assortment_40,new_choice_collection_40,new_offer_times_40 = new_data_w_at_least_2_products(n,assortments_40,choice_collection_40,offer_times_40)
print('the new size of the collection with offertimes at least 40 is ',len(new_assortment_40))

new_assortment_50,new_choice_collection_50,new_offer_times_50 = new_data_w_at_least_2_products(n,assortments_50,choice_collection_50,offer_times_50)
print('the new size of the collection with offertimes at least 50 is ',len(new_assortment_50))
 '''

" new_assortment_15,new_choice_collection_15,new_offer_times_15 = new_data_w_at_least_2_products(n,assortments_15,choice_collection_15,offer_times_15)\nprint('the new size of the collection with offertimes at least 15 is ',len(new_assortment_15))\n\nnew_assortment_20,new_choice_collection_20,new_offer_times_20 = new_data_w_at_least_2_products(n,assortments_20,choice_collection_20,offer_times_20)\nprint('the new size of the collection with offertimes at least 20 is ',len(new_assortment_20))\n\nnew_assortment_30,new_choice_collection_30,new_offer_times_30 = new_data_w_at_least_2_products(n,assortments_30,choice_collection_30,offer_times_30)\nprint('the new size of the collection with offertimes at least 30 is ',len(new_assortment_30))\n\nnew_assortment_40,new_choice_collection_40,new_offer_times_40 = new_data_w_at_least_2_products(n,assortments_40,choice_collection_40,offer_times_40)\nprint('the new size of the collection with offertimes at least 40 is ',len(new_assortment_40))\n\nnew_assortment_50,new_choice_collection_50,new_offer_times_50 = new_data_w_at_least_2_products(n,assortments_50,choice_collection_50,offer_times_50)\nprint('the new size of the collection with offertimes at least 50 is ',len(new_assortment_50))\n "

In [12]:
def collection_distribution_hev(n,collection):
    # generate mean 
    ''' mu_0 = np.random.uniform(2,3)
    mu_1n = np.random.uniform(-3,-2,n-1) '''
    # generate deterministic utilities for products
    
    ''' rho = -0.5 # prices and utilities are negatively correlated
    price_mean = np.mean(price[1:]) 
    price_std = np.std(price[1:])
    
    z = np.zeros(len(price[1:]))
    for i in range(len(z)):
        z[i] = (price[1:][i] - price_mean)/price_std
        
    mu_1n = np.zeros(len(z))
    normal_rvs = np.random.randn(len(mu_1n))
    for i in range(len(mu_1n)):
        mu_1n[i] = rho*z[i] + np.sqrt(1-rho**2)*normal_rvs[i] 
    ## deterministic utility of the outside option is strictly greater than the utilities of the products
    mu_0 = np.max(mu_1n) + 1
    # np.random.uniform(-2,2,n-1)
    mu = np.hstack((mu_0,mu_1n))
    
    scale_0 = 10
    scale_1n = np.random.uniform(0.04,1,n-1)
    scales = np.hstack((scale_0,scale_1n)) '''
    
    mu = np.random.uniform(-2,2,n)
    scales = np.random.uniform(0.04,2,n)
    
    sample_size = 10000
    utility_samples = np.array([gumbel_r.rvs(loc=mu, scale=scales) for _ in range(sample_size)])
    # generate covariance matrix with positive correlation
    # neg_cov = generate_negatively_correlated_covariance_matrix(n)
    # if is_positive_semidefinite(neg_cov): 
    #     sample_size = 10000
    #     utility_samples = np.random.multivariate_normal(mu,neg_cov,size=sample_size)
    # else:
    #     print('Negative correlation matrix error')
    
    collection_distribution = np.zeros((n,len(collection)))
    for i in range(len(collection)):
        curr_assortment = collection[i]
        curr_population = [[] for _ in range(sample_size)] 

        for j in range(sample_size):
            for k in curr_assortment:
                curr_population[j].append(utility_samples[j][k])
                # each sub list records only the utilities of products in the current assortment
                
        frequency = [0]*len(curr_assortment)
        for j in range(sample_size):
            max_index = np.argmax(np.array(curr_population[j]))
            # product is chosen iff the utility of the product is max in the assortment
            frequency[max_index] = frequency[max_index] +1 
            # update the frequency of product to be chosen
            
        prob = np.array(frequency)/np.sum(frequency)
        for j in range(len(curr_assortment)):
            collection_distribution[curr_assortment[j]][i] = prob[j]
            
    return collection_distribution

In [13]:
pred_offer_times_list = [20,30,40,50,60]
pred_instance_size = [50,50,50,50,50]

all_full_collections = [assortments_20,assortments_30,assortments_40,assortments_50,assortments_60]
all_full_offertimes = [offer_times_20,offer_times_30,offer_times_40,offer_times_50,offer_times_60]
full_collection_size = [len(offer_times_20),len(offer_times_30),len(offer_times_40),len(offer_times_50),len(offer_times_60)]

In [14]:
# full instance generation 
all_full_instances = []
for i in range(len(pred_offer_times_list)):
    
    full_instances_collection = []
    
    for j in range(pred_instance_size[i]):
        # generate true hev instance
        true_hev_instance = collection_distribution_hev(n,all_full_collections[i])
        full_instances_collection.append(true_hev_instance)

    
    all_full_instances.append(full_instances_collection)

In [15]:
def mnl_feasiblity_check(data,collection):
    
    actual_prod = np.unique(np.nonzero(data)[0]).tolist()
    start_time = time.time()
    model = gp.Model('mnl')
    model.setParam('OutputFlag', 0)
    v = model.addVars(n,name = 'v') # positive 
  
    for ass_idx in range(len(collection)):
        for i in collection[ass_idx]:
            model.addConstr(data[i][ass_idx]*sum(v[j] for j in collection[ass_idx])-v[i]==0)
    
    model.addConstrs(v[i]>=0 for i in range(data.shape[0]))
    model.addConstrs(v[i]<=100 for i in range(data.shape[0]))
    #model.setObjective(0,GRB.MAXIMIZE)
    model.setObjective(sum(v[i] for i in actual_prod),GRB.MAXIMIZE)
    model.optimize()
    used_time = time.time()-start_time
    
    # write the model 
    ''' print('write the model')
    model.write("out.sol")
    model.write("model.lp") ''' 
    obj = model.getObjective()
    print(obj.getValue())

    if model.Status == 3: #infeasible
        #return [0,model.Runtime]
        return [0, used_time]
    
    if model.Status == 2: #optimal
        soln = []
    
        for v in model.getVars():
            soln.append(v.x)
        #return [1,model.Runtime]
        if sum(soln)==0:  # the value of v cannot be all zero : recall that v here is actually exp(v) in MNL so ,all v should be positive
            return [0, used_time]
        
        for i in actual_prod:
            if soln[i] == 0:
                return[0,used_time]
        return [1,used_time]

In [16]:
import pyomo.environ as pyo
from pyomo.environ import *
from pyomo.opt import SolverFactory

def mnl_mle_pyo(data, collection,offertimes):
    n,m = data.shape
    model = pyo.ConcreteModel()
    model.v = pyo.Var(range(n), bounds=(-30,30))
    
    def obj_rule(model):
        obj = 0
        for i in range(len(collection)):
            for j in collection[i]:
                obj += offertimes[i]*data[j][i] * model.v[j]
            obj -= offertimes[i]*pyo.log(sum([pyo.exp(model.v[k]) for k in collection[i]]))
        return obj
    
    model.obj = pyo.Objective(rule=obj_rule, sense=pyo.maximize)
    
    model.outsideopt_constraint = pyo.Constraint(expr=model.v[0] == 0)
    opt = pyo.SolverFactory('ipopt')  # use iterior point method to solve convex optimizatio problem 
    results = opt.solve(model)
    
    if (results.solver.status == pyo.SolverStatus.ok) and (results.solver.termination_condition == pyo.TerminationCondition.optimal):
        v_values = [model.v[i].value for i in range(n)]
        obj_value = model.obj()
        prob = np.zeros((n,m)) 
        for j in range(m):
            curr_total_v = np.sum([np.exp(v_values[j]) for j in collection[j]])
            for i in collection[j]:
                prob[i,j] = np.exp(v_values[i])/curr_total_v  
        #model.pprint()
        return v_values, obj_value,prob,results.solver.time
    else:
        raise ValueError("Solver failed to find an optimal solution.")

In [17]:
def deterministic_term(data,offertimes):
    dt = 0 
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            if data[i][j] >0:
                dt = dt + offertimes[j]*data[i][j]*np.log(data[i][j])
    return dt,dt/np.sum(offertimes)

In [18]:
## record the limit loss of all instances
all_mnl_rep = []
all_mnl_rep_time = []

# in average 
all_mnl_kl_val = []
all_mnl_limit_loss = []
all_mnl_limit_prob = []
all_mnl_limit_runtime = []
all_mnl_infeasible_index = []

for i in range(len(pred_offer_times_list)):
    
    ## define contrainer for mnl representability
    mnl_rep_collection = []
    mnl_rep_time_collection = []
    mnl_infeasible_index_collection = []
    
    ## define container for mnl limit 
    mnl_kl_val_collection = []
    mnl_limit_loss_collection =[]
    mnl_limit_runtime_collection =[]
    mnl_limit_probability_collection =[]
    
    for j in range(pred_instance_size[i]):
        print(f'testing instance with offertimes {pred_offer_times_list[i]} : {j}th ')
 
        ## representability check of mnl
        curr_rep_result = mnl_feasiblity_check(all_full_instances[i][j],all_full_collections[i])
      
        # return [1/0,model.Runtime] # 1: representable 0: non-representable
        mnl_rep_collection.append(curr_rep_result[0])
        mnl_rep_time_collection.append(curr_rep_result[1])
        
        # check if representable
        if curr_rep_result[0] > 0:
            print(f'instance offertimes {pred_offer_times_list[i]}, {j}th is representable by mnl with runtime {curr_rep_result[1]}')
            mnl_limit_loss_collection.append(0)
            mnl_limit_runtime_collection.append(curr_rep_result[1])
            mnl_limit_probability_collection.append(all_full_instances[i][j])
          
        else:
            print(f'instance offertimes {pred_offer_times_list[i]}, {j}th is NOT representable by mnl')
            mnl_infeasible_index_collection.append(j)
            
            v_values,ll_value,mnl_limit_prob,ll_time = mnl_mle_pyo(all_full_instances[i][j],all_full_collections[i],all_full_offertimes[i])
            curr_deterministic_term, curr_avg_deterministic_term = deterministic_term(all_full_instances[i][j],all_full_offertimes[i])
            
            mnl_limit_loss_collection.append(-ll_value/np.sum(all_full_offertimes[i]) + curr_avg_deterministic_term)
            mnl_limit_probability_collection.append(mnl_limit_prob)
            mnl_limit_runtime_collection.append(ll_time)
           
            print('mnl kl loss is', mnl_limit_loss_collection[-1])
            print('mnl kl runtime is', ll_time)
    
    ## for each train instance [i][j] representability result is a number
    all_mnl_rep.append(mnl_rep_collection)
    all_mnl_rep_time.append(mnl_rep_time_collection) 
    all_mnl_infeasible_index.append(mnl_infeasible_index_collection)     
    
    ## for each train instance [i][j] limit loss result is a number
    all_mnl_limit_loss.append(mnl_limit_loss_collection)
    all_mnl_limit_runtime.append(mnl_limit_runtime_collection)
    ## for each train instance [i][j] limit probability is a matrix
    all_mnl_limit_prob.append(mnl_limit_probability_collection)

testing instance with offertimes 20 : 0th
Academic license - for non-commercial use only - expires 2024-12-10
Using license file /Users/autumn/gurobi.lic
0.0
instance offertimes 20, 0th is NOT representable by mnl
mnl kl loss is 0.001275545941287648
mnl kl runtime is 0.3866159915924072
testing instance with offertimes 20 : 1th
0.0
instance offertimes 20, 1th is NOT representable by mnl
mnl kl loss is 0.0007558154473981116
mnl kl runtime is 0.23500895500183105
testing instance with offertimes 20 : 2th
0.0
instance offertimes 20, 2th is NOT representable by mnl
mnl kl loss is 0.0007890976817576112
mnl kl runtime is 0.23380208015441895
testing instance with offertimes 20 : 3th
0.0
instance offertimes 20, 3th is NOT representable by mnl
mnl kl loss is 0.00020274523004359946
mnl kl runtime is 0.233201265335083
testing instance with offertimes 20 : 4th
0.0
instance offertimes 20, 4th is NOT representable by mnl
mnl kl loss is 0.0075104952968753635
mnl kl runtime is 0.362123966217041
testing instance with offertimes 20 : 5th
0.0
instance offertimes 20, 5th is NOT representable by mnl
mnl kl loss is 0.005961018075943514
mnl kl runtime is 0.237746000289917
testing instance with offertimes 20 : 6th
0.0
instance offertimes 20, 6th is NOT representable by mnl
mnl kl loss is 0.0005495891791306162
mnl kl runtime is 0.2793731689453125
testing instance with offertimes 20 : 7th
0.0
instance offertimes 20, 7th is NOT representable by mnl
mnl kl loss is 0.0005225539680820956
mnl kl runtime is 0.26259803771972656
testing instance with offertimes 20 : 8th
0.0
instance offertimes 20, 8th is NOT representable by mnl
mnl kl loss is 0.0015542883439704225
mnl kl runtime is 0.2537961006164551
testing instance with offertimes 20 : 9th
0.0
instance offertimes 20, 9th is NOT representable by mnl
mnl kl loss is 0.0037802142581500053
mnl kl runtime is 0.23441314697265625
testing instance with offertimes 20 : 10th
0.0
instance offertimes 20, 10th is NOT representable by mnl
mnl kl loss is 0.009879858368945227
mnl kl runtime is 0.23586320877075195
testing instance with offertimes 20 : 11th
0.0
instance offertimes 20, 11th is NOT representable by mnl
mnl kl loss is 0.0006953287705575573
mnl kl runtime is 0.2688617706298828
testing instance with offertimes 20 : 12th
0.0
instance offertimes 20, 12th is NOT representable by mnl
mnl kl loss is 0.0024030823546650204
mnl kl runtime is 0.24409222602844238
testing instance with offertimes 20 : 13th
0.0
instance offertimes 20, 13th is NOT representable by mnl
mnl kl loss is 0.0009589930457717388
mnl kl runtime is 0.25711894035339355
testing instance with offertimes 20 : 14th
0.0
instance offertimes 20, 14th is NOT representable by mnl
mnl kl loss is 0.013518987779867597
mnl kl runtime is 0.23305988311767578
testing instance with offertimes 20 : 15th
0.0
instance offertimes 20, 15th is NOT representable by mnl
mnl kl loss is 0.0025203470099337544
mnl kl runtime is 0.256572961807251
testing instance with offertimes 20 : 16th
0.0
instance offertimes 20, 16th is NOT representable by mnl
mnl kl loss is 0.009284852168147284
mnl kl runtime is 0.23566508293151855
testing instance with offertimes 20 : 17th
0.0
instance offertimes 20, 17th is NOT representable by mnl
mnl kl loss is 0.002541611088988871
mnl kl runtime is 0.2623310089111328
testing instance with offertimes 20 : 18th
0.0
instance offertimes 20, 18th is NOT representable by mnl
mnl kl loss is 0.0012628152106012314
mnl kl runtime is 0.23667502403259277
testing instance with offertimes 20 : 19th
0.0
instance offertimes 20, 19th is NOT representable by mnl
mnl kl loss is 0.00018524581036283294
mnl kl runtime is 0.2582991123199463
testing instance with offertimes 20 : 20th
0.0
instance offertimes 20, 20th is NOT representable by mnl
mnl kl loss is 0.010731631821612297
mnl kl runtime is 0.24755024909973145
testing instance with offertimes 20 : 21th
0.0
instance offertimes 20, 21th is NOT representable by mnl
mnl kl loss is 0.009082357294702137
mnl kl runtime is 0.26552295684814453
testing instance with offertimes 20 : 22th
0.0
instance offertimes 20, 22th is NOT representable by mnl
mnl kl loss is 0.006950125787757333
mnl kl runtime is 0.2539970874786377
testing instance with offertimes 20 : 23th
0.0
instance offertimes 20, 23th is NOT representable by mnl
mnl kl loss is 0.0008327273210517738
mnl kl runtime is 0.24796390533447266
testing instance with offertimes 20 : 24th
0.0
instance offertimes 20, 24th is NOT representable by mnl
mnl kl loss is 0.004941157924079453
mnl kl runtime is 0.25310206413269043
testing instance with offertimes 20 : 25th
0.0
instance offertimes 20, 25th is NOT representable by mnl
mnl kl loss is 0.0018689542859474662
mnl kl runtime is 0.24958491325378418
testing instance with offertimes 20 : 26th
0.0
instance offertimes 20, 26th is NOT representable by mnl
mnl kl loss is 0.005827703358417369
mnl kl runtime is 0.27324891090393066
testing instance with offertimes 20 : 27th
0.0
instance offertimes 20, 27th is NOT representable by mnl
mnl kl loss is 0.003374910287701982
mnl kl runtime is 0.2607560157775879
testing instance with offertimes 20 : 28th
0.0
instance offertimes 20, 28th is NOT representable by mnl
mnl kl loss is 0.0018873662372110855
mnl kl runtime is 0.2566361427307129
testing instance with offertimes 20 : 29th
0.0
instance offertimes 20, 29th is NOT representable by mnl
mnl kl loss is 0.00936318850044282
mnl kl runtime is 0.2562737464904785
testing instance with offertimes 20 : 30th
0.0
instance offertimes 20, 30th is NOT representable by mnl
mnl kl loss is 0.0001228444868227596
mnl kl runtime is 0.23922491073608398
testing instance with offertimes 20 : 31th
0.0
instance offertimes 20, 31th is NOT representable by mnl
mnl kl loss is 0.0010432967290340267
mnl kl runtime is 0.2338879108428955
testing instance with offertimes 20 : 32th
0.0
instance offertimes 20, 32th is NOT representable by mnl
mnl kl loss is 0.0015943129368617415
mnl kl runtime is 0.22750401496887207
testing instance with offertimes 20 : 33th
0.0
instance offertimes 20, 33th is NOT representable by mnl
mnl kl loss is 0.002399083918515288
mnl kl runtime is 0.23674321174621582
testing instance with offertimes 20 : 34th
0.0
instance offertimes 20, 34th is NOT representable by mnl
mnl kl loss is 0.012539336885939723
mnl kl runtime is 0.2304091453552246
testing instance with offertimes 20 : 35th
0.0
instance offertimes 20, 35th is NOT representable by mnl
mnl kl loss is 0.006070852912547942
mnl kl runtime is 0.2283940315246582
testing instance with offertimes 20 : 36th
0.0
instance offertimes 20, 36th is NOT representable by mnl
mnl kl loss is 0.015209464649554277
mnl kl runtime is 0.23035907745361328
testing instance with offertimes 20 : 37th
0.0
instance offertimes 20, 37th is NOT representable by mnl
mnl kl loss is 0.015294292919518393
mnl kl runtime is 0.22720909118652344
testing instance with offertimes 20 : 38th
0.0
instance offertimes 20, 38th is NOT representable by mnl
mnl kl loss is 0.01713781723726404
mnl kl runtime is 0.22773313522338867
testing instance with offertimes 20 : 39th
0.0
instance offertimes 20, 39th is NOT representable by mnl
mnl kl loss is 0.001300963796047494
mnl kl runtime is 0.22986388206481934
testing instance with offertimes 20 : 40th
0.0
instance offertimes 20, 40th is NOT representable by mnl
mnl kl loss is 0.0006691270729241028
mnl kl runtime is 0.3123929500579834
testing instance with offertimes 20 : 41th
0.0
instance offertimes 20, 41th is NOT representable by mnl
mnl kl loss is 6.0637830188781106e-05
mnl kl runtime is 0.23795104026794434
testing instance with offertimes 20 : 42th
0.0
instance offertimes 20, 42th is NOT representable by mnl
mnl kl loss is 0.005096853367592469
mnl kl runtime is 0.23607778549194336
testing instance with offertimes 20 : 43th
0.0
instance offertimes 20, 43th is NOT representable by mnl
mnl kl loss is 0.0026968626910532922
mnl kl runtime is 0.2244279384613037
testing instance with offertimes 20 : 44th
0.0
instance offertimes 20, 44th is NOT representable by mnl
mnl kl loss is 0.006711247102426099
mnl kl runtime is 0.2257847785949707
testing instance with offertimes 20 : 45th
0.0
instance offertimes 20, 45th is NOT representable by mnl
mnl kl loss is 0.005253334835929602
mnl kl runtime is 0.23383712768554688
testing instance with offertimes 20 : 46th
0.0
instance offertimes 20, 46th is NOT representable by mnl
mnl kl loss is 0.0026481420290821456
mnl kl runtime is 0.23081183433532715
testing instance with offertimes 20 : 47th
0.0
instance offertimes 20, 47th is NOT representable by mnl
mnl kl loss is 0.0017639404564455674
mnl kl runtime is 0.2411959171295166
testing instance with offertimes 20 : 48th
0.0
instance offertimes 20, 48th is NOT representable by mnl
mnl kl loss is 0.016872538343574772
mnl kl runtime is 0.24663996696472168
testing instance with offertimes 20 : 49th
0.0
instance offertimes 20, 49th is NOT representable by mnl
mnl kl loss is 0.004999622987597319
mnl kl runtime is 0.32619714736938477
testing instance with offertimes 30 : 0th
0.0
instance offertimes 30, 0th is NOT representable by mnl
mnl kl loss is 0.0013493460463437357
mnl kl runtime is 0.24510478973388672
testing instance with offertimes 30 : 1th
0.0
instance offertimes 30, 1th is NOT representable by mnl
mnl kl loss is 0.001675114080497364
mnl kl runtime is 0.2604222297668457
testing instance with offertimes 30 : 2th
0.0
instance offertimes 30, 2th is NOT representable by mnl
mnl kl loss is 0.00018347055496781284
mnl kl runtime is 0.26883721351623535
testing instance with offertimes 30 : 3th
0.0
instance offertimes 30, 3th is NOT representable by mnl
mnl kl loss is 0.0020246917882538185
mnl kl runtime is 0.24575090408325195
testing instance with offertimes 30 : 4th
0.0
instance offertimes 30, 4th is NOT representable by mnl
mnl kl loss is 0.00030932994303883854
mnl kl runtime is 0.2500309944152832
testing instance with offertimes 30 : 5th
0.0
instance offertimes 30, 5th is NOT representable by mnl
mnl kl loss is 0.0009011715980757895
mnl kl runtime is 0.30031585693359375
testing instance with offertimes 30 : 6th
0.0
instance offertimes 30, 6th is NOT representable by mnl
mnl kl loss is 0.001042139973747136
mnl kl runtime is 0.2644028663635254
testing instance with offertimes 30 : 7th
0.0
instance offertimes 30, 7th is NOT representable by mnl
mnl kl loss is 0.027712537292850614
mnl kl runtime is 0.24903297424316406
testing instance with offertimes 30 : 8th
0.0
instance offertimes 30, 8th is NOT representable by mnl
mnl kl loss is 0.0007543185652665318
mnl kl runtime is 0.27350473403930664
testing instance with offertimes 30 : 9th
0.0
instance offertimes 30, 9th is NOT representable by mnl
mnl kl loss is 0.010106568014790651
mnl kl runtime is 0.26192784309387207
testing instance with offertimes 30 : 10th
0.0
instance offertimes 30, 10th is NOT representable by mnl
mnl kl loss is 0.0014262057120723037
mnl kl runtime is 0.2305440902709961
testing instance with offertimes 30 : 11th
0.0
instance offertimes 30, 11th is NOT representable by mnl
mnl kl loss is 0.00031763211932200885
mnl kl runtime is 0.2320878505706787
testing instance with offertimes 30 : 12th
0.0
instance offertimes 30, 12th is NOT representable by mnl
mnl kl loss is 0.00019675007772779196
mnl kl runtime is 0.23767876625061035
testing instance with offertimes 30 : 13th
0.0
instance offertimes 30, 13th is NOT representable by mnl
mnl kl loss is 0.003400966965450114
mnl kl runtime is 0.2416222095489502
testing instance with offertimes 30 : 14th
0.0
instance offertimes 30, 14th is NOT representable by mnl
mnl kl loss is 7.873337349345588e-05
mnl kl runtime is 0.37612318992614746
testing instance with offertimes 30 : 15th
0.0
instance offertimes 30, 15th is NOT representable by mnl
mnl kl loss is 0.0005738613773722534
mnl kl runtime is 0.37279200553894043
testing instance with offertimes 30 : 16th
0.0
instance offertimes 30, 16th is NOT representable by mnl
mnl kl loss is 5.0212055997422844e-05
mnl kl runtime is 0.2806589603424072
testing instance with offertimes 30 : 17th
0.0
instance offertimes 30, 17th is NOT representable by mnl
mnl kl loss is 0.0011525877794821282
mnl kl runtime is 0.23697209358215332
testing instance with offertimes 30 : 18th
0.0
instance offertimes 30, 18th is NOT representable by mnl
mnl kl loss is 0.0001253676906136092
mnl kl runtime is 0.2630772590637207
testing instance with offertimes 30 : 19th
0.0
instance offertimes 30, 19th is NOT representable by mnl
mnl kl loss is 0.0009916011841217265
mnl kl runtime is 0.24834895133972168
testing instance with offertimes 30 : 20th
0.0
instance offertimes 30, 20th is NOT representable by mnl
mnl kl loss is 0.0015935255905437096
mnl kl runtime is 0.2994081974029541
testing instance with offertimes 30 : 21th
0.0
instance offertimes 30, 21th is NOT representable by mnl
mnl kl loss is 0.00026517939153486436
mnl kl runtime is 0.26667094230651855
testing instance with offertimes 30 : 22th
0.0
instance offertimes 30, 22th is NOT representable by mnl
mnl kl loss is 0.0008220231911636455
mnl kl runtime is 0.26328206062316895
testing instance with offertimes 30 : 23th
0.0
instance offertimes 30, 23th is NOT representable by mnl
mnl kl loss is 0.0023460191242651862
mnl kl runtime is 0.2615079879760742
testing instance with offertimes 30 : 24th
0.0
instance offertimes 30, 24th is NOT representable by mnl
mnl kl loss is 0.0016896398669323798
mnl kl runtime is 0.26372289657592773
testing instance with offertimes 30 : 25th
0.0
instance offertimes 30, 25th is NOT representable by mnl
mnl kl loss is 0.008240711382006993
mnl kl runtime is 0.2858419418334961
testing instance with offertimes 30 : 26th
0.0
instance offertimes 30, 26th is NOT representable by mnl
mnl kl loss is 0.0035109251587892576
mnl kl runtime is 0.2666170597076416
testing instance with offertimes 30 : 27th
0.0
instance offertimes 30, 27th is NOT representable by mnl
mnl kl loss is 0.0004837821579386503
mnl kl runtime is 0.31391000747680664
testing instance with offertimes 30 : 28th
0.0
instance offertimes 30, 28th is NOT representable by mnl
mnl kl loss is 0.0012698316666760467
mnl kl runtime is 0.25705695152282715
testing instance with offertimes 30 : 29th
0.0
instance offertimes 30, 29th is NOT representable by mnl
mnl kl loss is 0.001774997172563797
mnl kl runtime is 0.2523338794708252
testing instance with offertimes 30 : 30th
0.0
instance offertimes 30, 30th is NOT representable by mnl
mnl kl loss is 0.0006294547563328035
mnl kl runtime is 0.2570369243621826
testing instance with offertimes 30 : 31th
0.0
instance offertimes 30, 31th is NOT representable by mnl
mnl kl loss is 0.0006165506365274354
mnl kl runtime is 0.25975608825683594
testing instance with offertimes 30 : 32th
0.0
instance offertimes 30, 32th is NOT representable by mnl
mnl kl loss is 0.0019862003337504097
mnl kl runtime is 0.2672920227050781
testing instance with offertimes 30 : 33th
0.0
instance offertimes 30, 33th is NOT representable by mnl
mnl kl loss is 0.0007671424837657481
mnl kl runtime is 0.24152302742004395
testing instance with offertimes 30 : 34th
0.0
instance offertimes 30, 34th is NOT representable by mnl
mnl kl loss is 0.001026667420847338
mnl kl runtime is 0.34593987464904785
testing instance with offertimes 30 : 35th
0.0
instance offertimes 30, 35th is NOT representable by mnl
mnl kl loss is 0.00029852683720843487
mnl kl runtime is 0.23173785209655762
testing instance with offertimes 30 : 36th
0.0
instance offertimes 30, 36th is NOT representable by mnl
mnl kl loss is 0.010822717683979799
mnl kl runtime is 0.2335662841796875
testing instance with offertimes 30 : 37th
0.0
instance offertimes 30, 37th is NOT representable by mnl
mnl kl loss is 0.001626588221845915
mnl kl runtime is 0.22937393188476562
testing instance with offertimes 30 : 38th
0.0
instance offertimes 30, 38th is NOT representable by mnl
mnl kl loss is 0.012173799294203286
mnl kl runtime is 0.26616406440734863
testing instance with offertimes 30 : 39th
0.0
instance offertimes 30, 39th is NOT representable by mnl
mnl kl loss is 0.002977853863414759
mnl kl runtime is 0.24881887435913086
testing instance with offertimes 30 : 40th
0.0
instance offertimes 30, 40th is NOT representable by mnl
mnl kl loss is 0.002219735779772858
mnl kl runtime is 0.26708102226257324
testing instance with offertimes 30 : 41th
0.0
instance offertimes 30, 41th is NOT representable by mnl
mnl kl loss is 0.0011287423650334638
mnl kl runtime is 0.26084470748901367
testing instance with offertimes 30 : 42th
0.0
instance offertimes 30, 42th is NOT representable by mnl
mnl kl loss is 0.0016978151561408694
mnl kl runtime is 0.24848604202270508
testing instance with offertimes 30 : 43th
0.0
instance offertimes 30, 43th is NOT representable by mnl
mnl kl loss is 0.0023050871082574975
mnl kl runtime is 0.23222613334655762
testing instance with offertimes 30 : 44th
0.0
instance offertimes 30, 44th is NOT representable by mnl
mnl kl loss is 7.904149637671942e-05
mnl kl runtime is 0.2635340690612793
testing instance with offertimes 30 : 45th
0.0
instance offertimes 30, 45th is NOT representable by mnl
mnl kl loss is 0.0026881968528101874
mnl kl runtime is 0.262861967086792
testing instance with offertimes 30 : 46th
0.0
instance offertimes 30, 46th is NOT representable by mnl
mnl kl loss is 0.007432705190113853
mnl kl runtime is 0.2586522102355957
testing instance with offertimes 30 : 47th
0.0
instance offertimes 30, 47th is NOT representable by mnl
mnl kl loss is 0.0024128640931618817
mnl kl runtime is 0.24746394157409668
testing instance with offertimes 30 : 48th
0.0
instance offertimes 30, 48th is NOT representable by mnl
mnl kl loss is 0.0025838144456349355
mnl kl runtime is 0.24700427055358887
testing instance with offertimes 30 : 49th
0.0
instance offertimes 30, 49th is NOT representable by mnl
mnl kl loss is 0.0009350030758779604
mnl kl runtime is 0.26766395568847656
testing instance with offertimes 40 : 0th
0.0
instance offertimes 40, 0th is NOT representable by mnl
mnl kl loss is 0.002341796552134956
mnl kl runtime is 0.25138401985168457
testing instance with offertimes 40 : 1th
0.0
instance offertimes 40, 1th is NOT representable by mnl
mnl kl loss is 6.729286323137185e-05
mnl kl runtime is 0.24470019340515137
testing instance with offertimes 40 : 2th
0.0
instance offertimes 40, 2th is NOT representable by mnl
mnl kl loss is 0.0002157023955721149
mnl kl runtime is 0.22329115867614746
testing instance with offertimes 40 : 3th
0.0
instance offertimes 40, 3th is NOT representable by mnl
mnl kl loss is 0.002540580303030615
mnl kl runtime is 0.2246100902557373
testing instance with offertimes 40 : 4th
0.0
instance offertimes 40, 4th is NOT representable by mnl
mnl kl loss is 0.011414431786293616
mnl kl runtime is 0.23116207122802734
testing instance with offertimes 40 : 5th
0.0
instance offertimes 40, 5th is NOT representable by mnl
mnl kl loss is 0.00040282147977044325
mnl kl runtime is 0.22872614860534668
testing instance with offertimes 40 : 6th
0.0
instance offertimes 40, 6th is NOT representable by mnl
mnl kl loss is 0.0025422001989191534
mnl kl runtime is 0.22808599472045898
testing instance with offertimes 40 : 7th
0.0
instance offertimes 40, 7th is NOT representable by mnl
mnl kl loss is 1.8335968133637026e-05
mnl kl runtime is 0.2302570343017578
testing instance with offertimes 40 : 8th
0.0
instance offertimes 40, 8th is NOT representable by mnl
mnl kl loss is 0.0022897304131960228
mnl kl runtime is 0.22394204139709473
testing instance with offertimes 40 : 9th
0.0
instance offertimes 40, 9th is NOT representable by mnl
mnl kl loss is 0.000699786432013294
mnl kl runtime is 0.2313520908355713
testing instance with offertimes 40 : 10th
0.0
instance offertimes 40, 10th is NOT representable by mnl
mnl kl loss is 0.0026438869774876306
mnl kl runtime is 0.2717258930206299
testing instance with offertimes 40 : 11th
0.0
instance offertimes 40, 11th is NOT representable by mnl
mnl kl loss is 0.0004265955046752201

In [19]:
for i in range(len(pred_offer_times_list)):
    df_mnl_rep = pd.DataFrame({'ins_idx':list(range(pred_instance_size[i])),'mnl_rep':all_mnl_rep[i]})
    df_mnl_rep.to_csv('mnl/representability/'+str(pred_offer_times_list[i])+'.csv')

In [20]:
mnl_feasible_proportion_list = [np.sum(all_mnl_rep[x])/len(all_mnl_rep[x]) for x in range(len(pred_offer_times_list)) ]
mnl_rep_time_mean = [np.mean(all_mnl_rep_time[x]) for x in range(len(pred_offer_times_list)) ]
mnl_rep_time_se = [ np.std(all_mnl_rep_time[x])/np.sqrt(len(all_mnl_rep_time[x])) for x in range(len(pred_offer_times_list))  ]
mnl_rep_summary = pd.DataFrame({'offertimes':pred_offer_times_list,'collection_size':full_collection_size,
                                'mnl_rep':mnl_feasible_proportion_list,'mnl_rep_time':mnl_rep_time_mean,'mnl_rep_time_se':mnl_rep_time_se})
mnl_rep_summary.to_csv('mnl/mnl_rep_summary_hev_outside.csv')
mnl_rep_summary

   offertimes  collection_size  mnl_rep  mnl_rep_time  mnl_rep_time_se
0          20               29      0.0      0.004687         0.000426
1          30               24      0.0      0.003663         0.000110
2          40               19      0.0      0.003287         0.000117
3          50               15      0.0      0.002996         0.000120
4          60               13      0.0      0.002424         0.000071

In [21]:
# save infeasibe indices 
for i in range(len(pred_offer_times_list)):
    df_mnl_rep_infeas = pd.DataFrame(all_mnl_infeasible_index[i])
    df_mnl_rep_infeas.to_csv('mnl/rep_infeasibility/'+str(pred_offer_times_list[i])+'.csv')

In [22]:
# save solution: kl limit probability 
for i in range(len(pred_offer_times_list)):
    for j in range(pred_instance_size[i]):
        df_prob = pd.DataFrame(all_mnl_limit_prob[i][j])
        df_prob.to_csv('mnl/limit_prob/offertimes'+str(pred_offer_times_list[i])+'/prob'+str(j)+'.csv')

In [27]:
# record kl loss of mnl
for i in range(len(pred_offer_times_list)):
    df_mnl_loss = pd.DataFrame({'ins_idx':list(range(pred_instance_size[i])),
                                'mnl_kl_loss':all_mnl_limit_loss[i],
                                'mnl_kl_time':all_mnl_limit_runtime[i]})
    df_mnl_loss.to_csv('mnl/limit_loss/'+str(pred_offer_times_list[i])+'.csv')

In [23]:
# save kl loss 
mnl_kl_loss_mean = [np.mean(all_mnl_limit_loss[x]) for x in range(len(pred_offer_times_list)) ]
mnl_kl_loss_se = [ np.std(all_mnl_limit_loss[x])/np.sqrt(len(all_mnl_limit_loss[x])) for x in range(len(pred_offer_times_list)) ]

mnl_kl_time_mean = [np.mean(all_mnl_limit_runtime[x]) for x in range(len(pred_offer_times_list)) ]
mnl_kl_time_se = [ np.std(all_mnl_limit_runtime[x])/np.sqrt(len(all_mnl_limit_runtime[x])) for x in range(len(pred_offer_times_list)) ]

df_mnl_kl_loss = pd.DataFrame({'offertimes':pred_offer_times_list,'collection_size':full_collection_size,
                                  'mnl_kl_loss':mnl_kl_loss_mean, 'mnl_kl_loss_se':mnl_kl_loss_se,
                                'mnl_kl_time':mnl_kl_time_mean, 'mnl_kl_time_se':mnl_kl_time_se,
                                  })
df_mnl_kl_loss.to_csv('mnl/mnl_kl_summary_hev_outside.csv')
df_mnl_kl_loss

,offertimes,collection_size,mnl_kl_loss,mnl_kl_loss_se,mnl_kl_time,mnl_kl_time_se
0,20,29,0.004810,0.000677,0.251970,0.004541
1,30,24,0.002656,0.000637,0.264132,0.004407
2,40,19,0.003997,0.000869,0.256500,0.004360
3,50,15,0.002460,0.000482,0.263868,0.006925
4,60,13,0.002092,0.000517,0.265803,0.005346

In [24]:
mnl_rep_summary

   offertimes  collection_size  mnl_rep  mnl_rep_time  mnl_rep_time_se
0          20               29      0.0      0.004687         0.000426
1          30               24      0.0      0.003663         0.000110
2          40               19      0.0      0.003287         0.000117
3          50               15      0.0      0.002996         0.000120
4          60               13      0.0      0.002424         0.000071

In [25]:
df_mnl_rep_hev_summary = pd.read_csv('mnl/mnl_kl_summary_hev_outside.csv')
df_mnl_rep_hev_summary

,Unnamed: 0,offertimes,collection_size,mnl_kl_loss,mnl_kl_loss_se,mnl_kl_time,mnl_kl_time_se
0,0,20,29,0.004810,0.000677,0.251970,0.004541
1,1,30,24,0.002656,0.000637,0.264132,0.004407
2,2,40,19,0.003997,0.000869,0.256500,0.004360
3,3,50,15,0.002460,0.000482,0.263868,0.006925
4,4,60,13,0.002092,0.000517,0.265803,0.005346

In [28]:

all_rep_approx = []
all_rep_approx_mean = []
for i in range(len(pred_offer_times_list)):
    rep_approx = []
    df_all_mnl_kl_loss = pd.read_csv('mnl/limit_loss/'+str(pred_offer_times_list[i])+'.csv')
    mnl_avg_kl_loss_list = df_all_mnl_kl_loss['mnl_kl_loss'].tolist()
    for j in range(pred_instance_size[i]):
        if mnl_avg_kl_loss_list[j]<1e-6:
            rep_approx.append(j)
    all_rep_approx.append(rep_approx)
    all_rep_approx_mean.append(len(rep_approx)/pred_instance_size[i])
all_rep_approx_mean

[0.0, 0.0, 0.0, 0.0, 0.0]

In [29]:
df_mnl_rep_hev_summary['mnl_rep_approx'] = all_rep_approx_mean
df_mnl_rep_hev_summary.to_csv('mnl/mnl_rep_summary_hev_outside.csv')

In [30]:
df_mnl_rep_hev_summary

,Unnamed: 0,offertimes,collection_size,mnl_kl_loss,mnl_kl_loss_se,mnl_kl_time,mnl_kl_time_se,mnl_rep_approx
0,0,20,29,0.004810,0.000677,0.251970,0.004541,0.0
1,1,30,24,0.002656,0.000637,0.264132,0.004407,0.0
2,2,40,19,0.003997,0.000869,0.256500,0.004360,0.0
3,3,50,15,0.002460,0.000482,0.263868,0.006925,0.0
4,4,60,13,0.002092,0.000517,0.265803,0.005346,0.0

In [31]:
pd.DataFrame(all_full_instances[0][0])

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,0.2445,0.7737,0.6934,0.647,0.9506,0.6616,0.586,0.2402,0.2044,0.2445,...,0.4485,0.6329,0.4630,0.4271,0.3811,0.6508,0.5109,0.4494,0.3972,0.5132
1,0.7555,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.7359,0.6182,0.7555,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,0.0000,0.2263,0.0000,0.000,0.0000,0.0000,0.000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,0.0000,0.0000,0.3066,0.000,0.0000,0.0000,0.000,0.0239,0.0000,0.0000,...,0.1263,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,0.0000,0.0000,0.0000,0.353,0.0000,0.0000,0.000,0.0000,0.1774,0.0000,...,0.0000,0.3497,0.2852,0.2820,0.2600,0.0000,0.0000,0.0000,0.0000,0.0000
5,0.0000,0.0000,0.0000,0.000,0.0494,0.0000,0.000,0.0000,0.0000,0.0000,...,0.0000,0.0174,0.0000,0.0000,0.0000,0.0149,0.0041,0.0000,0.0000,0.0000
6,0.0000,0.0000,0.0000,0.000,0.0000,0.3384,0.000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.2518,0.0000,0.0000,0.3343,0.0000,0.2470,0.2235,0.0000
7,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.414,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.2909,0.0000,0.0000,0.0000,0.3036,0.0000,0.0000
8,0.0000,0.0000,0.0000,0.000,0.0000,0.0000,0.000,0.0000,0.0000,0.0000,...,0.4252,0.0000,0.0000,0.0000,0.3589,0.0000,0.4850,0.0000,0.3793,0.4868

In [33]:
error_instance_df = pd.read_csv('mccm_error_instance.csv')
error_instance_df

    Unnamed: 0  error_i  error_j
0            0        1       11
1            1        1       33
2            2        2       31
3            3        3       38
4            4        4        1
5            5        4        6
6            6        4        7
7            7        4       10
8            8        4       14
9            9        4       21
10          10        4       22
11          11        2       27

In [34]:
error_i = error_instance_df['error_i'].tolist()
error_j = error_instance_df['error_j'].tolist()

In [35]:
def create_new_list(A, error_i, error_j):
    # Create a set of (i, j) pairs for fast lookup of error positions
    error_set = set(zip(error_i, error_j))
    
    # Create a new list of lists by excluding the elements that are in the error_set
    A_prime = []
    for i, row in enumerate(A):
        new_row = [elem for j, elem in enumerate(row) if (i, j) not in error_set]
        A_prime.append(new_row)
    
    return A_prime

In [36]:
new_all_mnl_loss = create_new_list(all_mnl_limit_loss,error_i,error_j)
new_all_mnl_time = create_new_list(all_mnl_limit_runtime,error_i,error_j)
new_all_mnl_prob = create_new_list(all_mnl_limit_prob,error_i,error_j)

In [37]:
for i in range(len(pred_offer_times_list)):
    df_mnl_loss = pd.DataFrame({'mnl_kl_loss':new_all_mnl_loss[i],'mnl_kl_time':new_all_mnl_time[i]})
    df_mnl_loss.to_csv('mnl/limit_loss_new/'+str(pred_offer_times_list[i])+'.csv')

In [38]:
mnl_kl_loss_mean = [np.mean(new_all_mnl_loss[x]) for x in range(len(pred_offer_times_list)) ]
mnl_kl_loss_se = [ np.std(new_all_mnl_loss[x])/np.sqrt(len(new_all_mnl_loss[x])) for x in range(len(pred_offer_times_list)) ]

mnl_kl_time_mean = [np.mean(new_all_mnl_time[x]) for x in range(len(pred_offer_times_list)) ]
mnl_kl_time_se = [ np.std(new_all_mnl_time[x])/np.sqrt(len(new_all_mnl_time[x])) for x in range(len(pred_offer_times_list)) ]

df_mnl_kl_loss = pd.DataFrame({'offertimes':pred_offer_times_list,'collection_size':full_collection_size,
                                  'mnl_kl_loss':mnl_kl_loss_mean, 'mnl_kl_loss_se':mnl_kl_loss_se,
                                'mnl_kl_time':mnl_kl_time_mean, 'mnl_kl_time_se':mnl_kl_time_se
                                  })
df_mnl_kl_loss.to_csv('mnl/mnl_kl_summary_NEW.csv')
df_mnl_kl_loss

,offertimes,collection_size,mnl_kl_loss,mnl_kl_loss_se,mnl_kl_time,mnl_kl_time_se
0,20,29,0.004810,0.000677,0.251970,0.004541
1,30,24,0.002744,0.000661,0.265271,0.004514
2,40,19,0.003656,0.000835,0.256000,0.004525
3,50,15,0.002477,0.000491,0.264122,0.007062
4,60,13,0.002247,0.000593,0.264904,0.005009

In [39]:
all_rep = []
rep_mean = []
for i in range(len(pred_instance_size)):
    rep_lst = []
    for j in range(len(new_all_mnl_loss[i])):
        if new_all_mnl_loss[i][j] <1e-6:
            rep_lst.append(j)
    df_rep = pd.DataFrame(rep_lst)
    df_rep.to_csv('mnl/representability_new/'+str(pred_offer_times_list[i])+'.csv')
    all_rep.append(rep_lst)
    rep_mean.append(len(rep_lst)/len(new_all_mnl_loss[i]))
rep_mean

[0.0, 0.0, 0.0, 0.0, 0.0]

In [40]:
df_rep = pd.DataFrame({'offertimes':pred_offer_times_list,'collection_size':full_collection_size,'mnl_rep':rep_mean})
df_rep.to_csv('mnl/mnl_rep_summary_NEW.csv')
df_rep

   offertimes  collection_size  mnl_rep
0          20               29      0.0
1          30               24      0.0
2          40               19      0.0
3          50               15      0.0
4          60               13      0.0